apiVersion: v1
kind: Pod
metadata:
  name: nginx-web
  labels:
    app: nginx-web
spec:
  containers:
  - name: secure-container
    image: nginx:1.10.1-alpine
    ports:
    - containerPort: 8080
    securityContext:
      runAsUser: 1001                   
      runAsGroup: 1001                  
  securityContext:
    runAsNonRoot: true                             
